version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diary
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: